/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdHocLineItem {
  'createdAt' : bigint,
  'description' : string,
  'amountCents' : bigint,
}
export interface AlternativeWindow {
  'duration' : string,
  'date' : string,
  'time' : string,
}
export type AuditAction = { 'SupportTicketOpened' : null } |
  { 'AccountFrozen' : null } |
  { 'BookingDeleted' : null } |
  { 'GdprExportRequested' : null } |
  { 'SupportTicketResolved' : null } |
  { 'AccountUnfrozen' : null } |
  { 'ServiceCompletionUpdated' : null } |
  { 'SubscriptionRecorded' : null } |
  { 'GdprAnonymizationRequested' : null } |
  { 'PriceAdjusted' : null } |
  { 'AccountAnonymized' : null } |
  { 'ConsentRecorded' : null } |
  { 'PaymentDeleted' : null } |
  { 'BookingDeclined' : null } |
  { 'SubscriptionCancelled' : null } |
  { 'DiscountApplied' : null } |
  { 'AdminAccessRevoked' : null } |
  { 'AdHocJobCreated' : null } |
  { 'SitterDeleted' : null } |
  { 'GdprExportDownloaded' : null } |
  { 'SitterDeactivated' : null } |
  { 'SitterReactivated' : null } |
  { 'AdminAccessGranted' : null };
export interface AvailabilityEntry {
  'startTime' : bigint,
  'endTime' : bigint,
  'dayOfWeek' : bigint,
}
export interface BookingAgreements {
  'terms' : boolean,
  'termsVersion' : bigint,
  'cancellationPolicy' : boolean,
  'communications' : boolean,
  'nonEmploymentAck' : boolean,
  'privacy' : boolean,
  'callRequest' : boolean,
}
export interface BookingGroup {
  'startTime' : string,
  'status' : GroupStatus,
  'clientInfo' : ClientInfo,
  'sitterId' : bigint,
  'endTime' : string,
  'createdAt' : Time,
  'occurrenceIds' : Array<bigint>,
  'recurrenceRule' : RecurrenceRule,
  'serviceIds' : Array<string>,
  'groupId' : string,
  'petInfo' : Array<PetInfo>,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'declined' : null };
export interface CRMClient {
  'clientName' : string,
  'lastBookingDate' : bigint,
  'tags' : Array<string>,
  'clientEmail' : string,
  'totalSpent' : number,
  'clientPhone' : string,
  'bookingCount' : bigint,
}
export interface ClientInfo {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface CoBookingAssignment {
  'bookingId' : bigint,
  'assignments' : Array<[bigint, string]>,
  'teamId' : string,
  'splitAmounts' : Array<[bigint, bigint]>,
}
export interface Creation {
  'startTime' : [] | [Time],
  'status' : ServiceStatus,
  'bookingId' : Id,
  'sitterId' : Id,
  'notes' : string,
}
export interface Creation__1 {
  'bio' : string,
  'birthdate' : [] | [bigint],
  'name' : string,
  'hourlyRate' : bigint,
  'photoUrl' : string,
  'phone' : string,
  'location' : string,
  'services' : Array<string>,
}
export interface Creation__2 {
  'method' : PaymentMethod,
  'bookingId' : Id,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'splits' : Array<PaymentSplit>,
}
export interface Creation__3 {
  'tip' : [] | [bigint],
  'agreements' : [] | [BookingAgreements],
  'endDate' : Time,
  'serviceSchedule' : [] | [Array<DayServiceSchedule>],
  'isRecurring' : boolean,
  'clientName' : string,
  'adHocClientContact' : [] | [string],
  'pets' : Array<Pet>,
  'clientEmail' : string,
  'recurrencePattern' : [] | [RecurrencePattern],
  'recurrenceEndDate' : [] | [Time],
  'notes' : string,
  'clientPhone' : string,
  'isAdHoc' : [] | [boolean],
  'schedule' : [] | [Array<DaySchedule>],
  'callRequest' : [] | [boolean],
  'sitterIds' : Array<bigint>,
  'services' : Array<string>,
  'startDate' : Time,
}
export interface CredentialChecklist {
  'isProfessionalMember' : [] | [boolean],
  'hasCertificationOrTraining' : [] | [boolean],
  'hasReferences' : [] | [boolean],
  'hasBusinessLicense' : [] | [boolean],
  'isInsuredAndBonded' : [] | [boolean],
  'usesServiceAgreement' : [] | [boolean],
  'hasBackgroundCheck' : [] | [boolean],
}
export interface DaySchedule { 'date' : Time, 'slots' : Array<TimeSlot> }
export interface DayServiceSchedule {
  'date' : string,
  'slots' : Array<ServiceSlot>,
}
export interface DealOffer {
  'id' : string,
  'redeemedBy' : Array<string>,
  'redeemedCount' : bigint,
  'couponCode' : string,
  'discountValue' : number,
  'sitterId' : bigint,
  'discountType' : DiscountType,
  'description' : string,
  'sentAt' : bigint,
  'isActive' : boolean,
  'expirationDate' : bigint,
  'maxUses' : [] | [bigint],
  'clientEmails' : Array<string>,
}
export type DiscountType = { 'fixed' : null } |
  { 'percent' : null };
export interface DutyAssignment {
  'status' : { 'assigned' : null } |
    { 'done' : null } |
    { 'inProgress' : null },
  'tasks' : Array<DutyTask>,
  'createdAt' : bigint,
  'description' : string,
  'assignedSitterId' : bigint,
  'dutyId' : string,
}
export interface DutyTask {
  'doneAt' : [] | [bigint],
  'done' : boolean,
  'taskId' : string,
  'taskLabel' : string,
}
export type GroupStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type Id = bigint;
export interface JobThread {
  'status' : { 'closed' : null } |
    { 'open' : null },
  'bookingId' : bigint,
  'createdAt' : bigint,
  'duties' : Array<DutyAssignment>,
  'teamId' : string,
  'threadId' : string,
}
export interface Message {
  'content' : string,
  'timestamp' : Time,
  'senderName' : string,
  'senderId' : [] | [Principal],
}
export interface NotificationRecord {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'notificationType' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'recipientSitterId' : bigint,
}
export interface OccurrenceAvailability {
  'date' : Time,
  'available' : boolean,
  'conflictReason' : [] | [string],
}
export interface PageComponentVisibility {
  'showAvailability' : boolean,
  'showCredentials' : boolean,
  'showResponseTime' : boolean,
  'showCertifications' : boolean,
  'showPetTypes' : boolean,
  'showStats' : boolean,
  'showGallery' : boolean,
  'showPromo' : boolean,
  'showReviews' : boolean,
  'showRepeatClients' : boolean,
}
export type PaymentMethod = { 'stripe' : null } |
  { 'manual' : null };
export type PaymentMethodDetails = { 'venmo' : { 'handle' : string } } |
  { 'cash' : { 'instructions' : string } } |
  { 'applePayCash' : { 'sitterPhone' : string } };
export interface PaymentSplit {
  'sitterId' : Id,
  'paid' : boolean,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null };
export interface Pet {
  'petNotes' : [] | [string],
  'petName' : string,
  'petType' : string,
  'breed' : [] | [string],
}
export interface PetInfo {
  'name' : string,
  'type' : string,
  'notes' : string,
  'breed' : string,
}
export interface Public {
  'id' : bigint,
  'bio' : string,
  'owner' : [] | [Principal],
  'birthdate' : [] | [bigint],
  'name' : string,
  'hourlyRate' : bigint,
  'photoUrl' : string,
  'isAnonymized' : [] | [boolean],
  'isActive' : boolean,
  'serviceRates' : Array<Public__1>,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
  'location' : string,
  'services' : Array<string>,
}
export interface Public__1 { 'service' : string, 'ratePerHour' : bigint }
export interface Public__2 {
  'id' : Id,
  'startTime' : [] | [Time],
  'status' : ServiceStatus,
  'bookingId' : Id,
  'sitterId' : Id,
  'createdAt' : Time,
  'stopTime' : [] | [Time],
  'notes' : string,
}
export interface Public__3 {
  'bookingId' : bigint,
  'sitterId' : bigint,
  'clientName' : string,
  'createdAt' : Time,
  'amountCents' : bigint,
}
export interface Public__4 {
  'id' : string,
  'status' : TicketStatus,
  'sitterId' : Principal,
  'createdAt' : bigint,
  'accessRevokedAt' : [] | [bigint],
  'accessGrantedAt' : [] | [bigint],
  'issue' : string,
  'adminNotes' : [] | [string],
  'sitterName' : string,
  'resolvedAt' : [] | [bigint],
}
export interface Public__5 {
  'bookingId' : bigint,
  'createdAt' : Time,
  'reviewText' : string,
  'rating' : number,
}
export interface Public__6 {
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'originalAmount' : [] | [bigint],
  'bookingId' : Id,
  'actualEndTime' : [] | [Time],
  'discountAmount' : [] | [bigint],
  'adHocItems' : Array<AdHocLineItem>,
  'confirmedAt' : [] | [Time],
  'discountPercent' : [] | [bigint],
  'paidDate' : [] | [string],
  'manualConfirmedBy' : [] | [Principal],
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'paymentMethodDetails' : [] | [PaymentMethodDetails],
  'stripePaymentIntentId' : [] | [string],
  'splits' : Array<PaymentSplit>,
  'completionNotes' : [] | [string],
}
export interface Public__7 {
  'id' : Id,
  'action' : AuditAction,
  'snapshot' : string,
  'entityId' : bigint,
  'timestamp' : Time,
  'entityType' : string,
  'deletedBy' : Principal,
}
export interface Public__8 {
  'id' : Id,
  'tip' : [] | [bigint],
  'agreements' : [] | [BookingAgreements],
  'status' : BookingStatus,
  'paymentSessionId' : [] | [string],
  'endDate' : Time,
  'serviceSchedule' : [] | [Array<DayServiceSchedule>],
  'isRecurring' : boolean,
  'clientName' : string,
  'adHocClientContact' : [] | [string],
  'createdAt' : Time,
  'pets' : Array<Pet>,
  'clientEmail' : string,
  'recurrencePattern' : [] | [RecurrencePattern],
  'recurrenceEndDate' : [] | [Time],
  'alternativeWindows' : [] | [Array<AlternativeWindow>],
  'notes' : string,
  'clientPhone' : string,
  'stripePaymentIntentId' : [] | [string],
  'isAdHoc' : boolean,
  'schedule' : [] | [Array<DaySchedule>],
  'declineReason' : [] | [string],
  'sitterIds' : Array<bigint>,
  'services' : Array<string>,
  'startDate' : Time,
}
export type RecurrencePattern = { 'monthly' : null } |
  { 'biweekly' : null } |
  { 'weekly' : null };
export interface RecurrenceRule {
  'occurrenceCount' : [] | [bigint],
  'pattern' : RecurrencePattern,
  'endDate' : [] | [Time],
  'daysOfWeek' : Uint8Array,
  'startDate' : Time,
}
export interface RecurringGroupCreation {
  'agreements' : BookingAgreements,
  'startTime' : string,
  'totalCostCents' : bigint,
  'clientInfo' : ClientInfo,
  'sitterId' : bigint,
  'endTime' : string,
  'serviceDuration' : bigint,
  'recurrenceRule' : RecurrenceRule,
  'serviceIds' : Array<string>,
  'petInfo' : Array<PetInfo>,
}
export interface ServiceSlot {
  'service' : string,
  'startTime' : string,
  'sitterId' : bigint,
  'endTime' : string,
  'durationMinutes' : bigint,
  'ratePerHour' : bigint,
}
export type ServiceStatus = { 'completed' : null } |
  { 'checkedIn' : null } |
  { 'issueReported' : null } |
  { 'inProgress' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SitterBookingStats {
  'completedVisits' : bigint,
  'totalBookings' : bigint,
  'uniqueClients' : bigint,
  'repeatClients' : bigint,
}
export interface SitterLicenseStatus {
  'trialDaysRemaining' : [] | [bigint],
  'trialActive' : boolean,
  'isFrozen' : boolean,
  'isGrandfathered' : boolean,
  'stripeSubscriptionId' : [] | [string],
  'subscriptionStatus' : string,
  'stripeCustomerId' : [] | [string],
  'isSubscribed' : boolean,
  'isLicensed' : boolean,
  'trialStartedAt' : [] | [bigint],
}
export interface SitterProfileV2Update {
  'sitterId' : bigint,
  'pageComponents' : [] | [PageComponentVisibility],
  'serviceRadius' : [] | [bigint],
  'serviceZip' : [] | [string],
  'acceptingNewClients' : [] | [boolean],
  'bannerUrl' : [] | [string],
  'certificationsList' : [] | [Array<string>],
  'responseTime' : [] | [string],
  'petTypesServed' : [] | [Array<string>],
  'credentialChecklist' : [] | [CredentialChecklist],
  'pinnedPromoOfferId' : [] | [string],
  'galleryPhotos' : [] | [Array<string>],
}
export interface SitterPublicV2Extension {
  'pageComponents' : [] | [PageComponentVisibility],
  'serviceRadius' : [] | [bigint],
  'serviceZip' : [] | [string],
  'acceptingNewClients' : [] | [boolean],
  'bannerUrl' : [] | [string],
  'certificationsList' : [] | [Array<string>],
  'responseTime' : [] | [string],
  'petTypesServed' : [] | [Array<string>],
  'credentialChecklist' : [] | [CredentialChecklist],
  'pinnedPromoOfferId' : [] | [string],
  'galleryPhotos' : [] | [Array<string>],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionRecord {
  'isFrozen' : boolean,
  'frozenAt' : [] | [bigint],
  'stripeSubscriptionId' : [] | [string],
  'trialExpiredEmailSent' : [] | [boolean],
  'isFreePlan' : [] | [boolean],
  'stripeCustomerId' : [] | [string],
  'lastPaymentAt' : [] | [bigint],
  'isSubscribed' : boolean,
  'trialReminderSent' : [] | [boolean],
  'subscriptionStartedAt' : [] | [bigint],
  'trialStartedAt' : [] | [bigint],
}
export interface Team {
  'status' : { 'active' : null } |
    { 'dissolved' : null },
  'name' : string,
  'createdAt' : bigint,
  'memberIds' : Array<bigint>,
  'teamId' : string,
  'splitPercentages' : Array<[bigint, bigint]>,
}
export interface TeamInvite {
  'status' : { 'expired' : null } |
    { 'pending' : null } |
    { 'accepted' : null } |
    { 'declined' : null },
  'expiresAt' : bigint,
  'inviteId' : string,
  'createdAt' : bigint,
  'toSitterId' : [] | [bigint],
  'inviteCode' : string,
  'teamId' : [] | [string],
  'fromSitterId' : bigint,
}
export interface TeamMessage {
  'msgId' : string,
  'content' : string,
  'msgType' : { 'channel' : null } |
    { 'jobThread' : null },
  'threadBookingId' : [] | [bigint],
  'senderSitterId' : bigint,
  'sentAt' : bigint,
  'teamId' : string,
}
export type TicketStatus = { 'resolved' : null } |
  { 'adminAccessing' : null } |
  { 'open' : null };
export type Time = bigint;
export interface TimeSlot { 'startTime' : Time, 'endTime' : Time }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Update {
  'id' : Id,
  'bio' : string,
  'name' : string,
  'hourlyRate' : bigint,
  'photoUrl' : string,
  'isActive' : boolean,
  'phone' : string,
  'location' : string,
  'services' : Array<string>,
}
export interface UpdateSplits {
  'bookingId' : Id,
  'splits' : Array<PaymentSplit>,
}
export interface UpdateStopTime { 'id' : Id, 'stopTime' : Time }
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptInviteByCode' : ActorMethod<
    [string],
    { 'ok' : Team } |
      { 'err' : string }
  >,
  'addMessage' : ActorMethod<[Id, string, string], undefined>,
  'addPhotoConsentLog' : ActorMethod<
    [bigint, string, boolean, boolean, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adjustPaymentPrice' : ActorMethod<
    [Id, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAnonymizeSitter' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminExportSitterData' : ActorMethod<
    [Id],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'anonymizeSitterAccount' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveSitterApplication' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCoSitters' : ActorMethod<
    [bigint, string, Array<[bigint, string]>],
    { 'ok' : CoBookingAssignment } |
      { 'err' : string }
  >,
  'assignDuty' : ActorMethod<
    [string, bigint, string, Array<string>],
    { 'ok' : DutyAssignment } |
      { 'err' : string }
  >,
  'assignSitterToFreePlan' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'backfillSitterHandles' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'cancelBookingByClient' : ActorMethod<
    [Id, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'cancelRecurringGroup' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'cancelSubscription' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'checkAndSendTrialReminder' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'checkSittersAvailabilityForRebook' : ActorMethod<
    [Array<bigint>, Array<string>, Array<string>],
    Array<{ 'sitterId' : bigint, 'available' : boolean, 'reason' : string }>
  >,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'clearAllData' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'confirmManualPayment' : ActorMethod<[Id], undefined>,
  'confirmManualPaymentWithEmail' : ActorMethod<
    [Id, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'confirmRecurringGroup' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmRecurringOccurrence' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmStripeCheckoutSession' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Create an ad hoc job record for a non-app client.
   * / CRITICAL: clientEmail and clientPhone are always empty — the non-app client
   * / is never contacted by the app under any circumstances.
   * / offAppClientAcknowledged MUST be true — sitter affirms the client has no Pawspect relationship.
   */
  'createAdHocJob' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      [] | [bigint],
      [] | [string],
      Array<string>,
      [] | [string],
      boolean,
    ],
    { 'ok' : Public__8 } |
      { 'err' : string }
  >,
  'createBooking' : ActorMethod<[Creation__3], Public__8>,
  'createBookingWithCoupon' : ActorMethod<
    [Creation__3, [] | [string]],
    Public__8
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDealOffer' : ActorMethod<
    [
      bigint,
      DiscountType,
      number,
      string,
      bigint,
      Array<string>,
      [] | [bigint],
    ],
    { 'ok' : DealOffer } |
      { 'err' : string }
  >,
  'createJobThread' : ActorMethod<
    [string, bigint],
    { 'ok' : JobThread } |
      { 'err' : string }
  >,
  'createNotification' : ActorMethod<
    [bigint, string, string, string],
    NotificationRecord
  >,
  'createPayment' : ActorMethod<[Creation__2], Public__6>,
  'createRecurringBookingGroup' : ActorMethod<
    [RecurringGroupCreation],
    { 'ok' : BookingGroup } |
      { 'err' : string }
  >,
  'createSitterProfile' : ActorMethod<[Creation__1], Public>,
  /**
   * / Create a proper subscription checkout session using the configured Stripe Price ID.
   * / This is what the sitter portal "Subscribe Now" button should call.
   */
  'createSubscriptionCheckoutSession' : ActorMethod<[string, string], string>,
  'createTeamInvite' : ActorMethod<
    [bigint, string, Array<[bigint, bigint]>],
    { 'ok' : TeamInvite } |
      { 'err' : string }
  >,
  'declineBookingRequest' : ActorMethod<
    [Id, string, Array<AlternativeWindow>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'declineRecurringOccurrence' : ActorMethod<
    [
      bigint,
      string,
      Array<{ 'duration' : string, 'date' : string, 'time' : string }>,
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBooking' : ActorMethod<[Id], { 'ok' : null } | { 'err' : string }>,
  'deletePayment' : ActorMethod<[Id], { 'ok' : null } | { 'err' : string }>,
  'deleteSitterProfile' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'dissolveTeamAdmin' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'exportSitterData' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'fixSitterZipCodes' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'freezeSitterAccount' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateTeamInviteLink' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getActiveSitters' : ActorMethod<[], Array<Public>>,
  /**
   * / Return all ad hoc jobs for a given sitter (isAdHoc = true and sitterId in sitterIds).
   */
  'getAdHocJobsBySitter' : ActorMethod<[bigint], Array<Public__8>>,
  'getAdminBookingAnalytics' : ActorMethod<
    [],
    {
      'serviceTypeDurations' : Array<[string, number]>,
      'serviceTypeCounts' : Array<[string, bigint]>,
      'avgServiceDurationMinutes' : number,
      'avgTimeToPaymentMinutes' : number,
      'serviceTypeRevenue' : Array<[string, bigint]>,
    }
  >,
  'getAdminBookingStats' : ActorMethod<
    [],
    {
      'pendingCount' : bigint,
      'cancelledCount' : bigint,
      'completedCount' : bigint,
      'confirmedCount' : bigint,
      'pendingRevenue' : bigint,
      'totalRevenue' : bigint,
      'confirmedRevenue' : bigint,
    }
  >,
  'getAdminNotificationEmail' : ActorMethod<[], string>,
  'getAdminPendingRevenue' : ActorMethod<[], bigint>,
  'getAdminPendingRevenueBreakdown' : ActorMethod<
    [],
    Array<{ 'bookingId' : bigint, 'clientName' : string, 'amount' : bigint }>
  >,
  'getAllBookings' : ActorMethod<[], Array<Public__8>>,
  'getAllPayments' : ActorMethod<[], Array<Public__6>>,
  'getAllSitterHandles' : ActorMethod<[], Array<[bigint, string]>>,
  'getAllSitters' : ActorMethod<[], Array<Public>>,
  'getAllSubscriptionStates' : ActorMethod<
    [],
    Array<[bigint, SubscriptionRecord]>
  >,
  'getAllTeamsAdmin' : ActorMethod<[], Array<Team>>,
  /**
   * / Returns current usage counts and configured limits.
   */
  'getApiUsageLimits' : ActorMethod<
    [],
    {
      'monthlyCount' : bigint,
      'monthlyLimit' : bigint,
      'dailyCount' : bigint,
      'dailyLimit' : bigint,
      'resetDate' : string,
    }
  >,
  'getAuditLog' : ActorMethod<[], Array<Public__7>>,
  'getAvailableHourlyWindows' : ActorMethod<
    [string],
    Array<
      {
        'startTime' : string,
        'availableSitterCount' : bigint,
        'endTime' : string,
      }
    >
  >,
  'getAvailableSittersForWindow' : ActorMethod<
    [string, string, string],
    Array<Public>
  >,
  'getBookingHeatmapData' : ActorMethod<
    [],
    Array<
      {
        'pendingCount' : bigint,
        'sitterId' : bigint,
        'date' : string,
        'hour' : bigint,
        'confirmedCount' : bigint,
        'sitterName' : string,
      }
    >
  >,
  'getBookingsByClientEmail' : ActorMethod<[string], Array<Public__8>>,
  'getBookingsByClientPhone' : ActorMethod<[string], Array<Public__8>>,
  'getBookingsBySitter' : ActorMethod<[Id], Array<Public__8>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoBookingAssignment' : ActorMethod<[bigint], [] | [CoBookingAssignment]>,
  'getCompletedBookingsByContact' : ActorMethod<
    [string, string],
    Array<Public__8>
  >,
  'getCompletedBookingsCount' : ActorMethod<[bigint], bigint>,
  'getDealOffersBySitter' : ActorMethod<[bigint], Array<DealOffer>>,
  'getGrantedAdmins' : ActorMethod<[], Array<Principal>>,
  'getJobThread' : ActorMethod<[bigint], [] | [JobThread]>,
  'getJobThreadMessages' : ActorMethod<[bigint, bigint], Array<TeamMessage>>,
  'getJobThreadsForTeam' : ActorMethod<[string], Array<JobThread>>,
  'getMessages' : ActorMethod<[Id], Array<Message>>,
  'getMySupportTickets' : ActorMethod<[], Array<Public__4>>,
  'getMyTeams' : ActorMethod<[], Array<Team>>,
  'getNotificationsBySitter' : ActorMethod<[bigint], Array<NotificationRecord>>,
  'getPayment' : ActorMethod<[Id], [] | [Public__6]>,
  'getPaymentAuditLog' : ActorMethod<[Id], Array<Public__7>>,
  'getPaymentsByBookingIds' : ActorMethod<[Array<string>], Array<Public__6>>,
  'getPendingInvitesForSitter' : ActorMethod<[bigint], Array<TeamInvite>>,
  'getPublicSitterProfile' : ActorMethod<
    [string],
    [] | [
      {
        'id' : bigint,
        'bio' : [] | [string],
        'reviews' : Array<
          {
            'clientName' : string,
            'createdAt' : bigint,
            'comment' : [] | [string],
            'rating' : bigint,
          }
        >,
        'name' : string,
        'badges' : Array<string>,
        'isActive' : boolean,
        'averageRating' : number,
        'profilePhotoUrl' : [] | [string],
        'reviewCount' : bigint,
        'services' : Array<
          {
            'serviceName' : string,
            'duration' : [] | [string],
            'price' : number,
          }
        >,
      }
    ]
  >,
  'getRecurringGroup' : ActorMethod<[string], [] | [BookingGroup]>,
  'getRecurringGroupsByClient' : ActorMethod<[string], Array<BookingGroup>>,
  'getRecurringGroupsBySitter' : ActorMethod<[bigint], Array<BookingGroup>>,
  'getReviewsBySitter' : ActorMethod<[Id], Array<Public__5>>,
  'getServiceLogsByBooking' : ActorMethod<[Id], Array<Public__2>>,
  'getSitterAvailability' : ActorMethod<[Id], Array<AvailabilityEntry>>,
  'getSitterBookingStats' : ActorMethod<[bigint], SitterBookingStats>,
  'getSitterClientsForCRM' : ActorMethod<[bigint], Array<CRMClient>>,
  'getSitterCredentials' : ActorMethod<[bigint], [] | [CredentialChecklist]>,
  'getSitterExtendedPublic' : ActorMethod<
    [bigint],
    [] | [SitterPublicV2Extension]
  >,
  'getSitterHandle' : ActorMethod<[Id], [] | [string]>,
  'getSitterLicenseStatus' : ActorMethod<[], SitterLicenseStatus>,
  'getSitterPageComponents' : ActorMethod<
    [bigint],
    [] | [PageComponentVisibility]
  >,
  'getSitterPrivateData' : ActorMethod<
    [bigint],
    {
        'ok' : {
          'emergencyContact' : [] | [string],
          'earningsGoal' : [] | [bigint],
        }
      } |
      { 'err' : string }
  >,
  'getSitterProfile' : ActorMethod<[Id], Public>,
  'getSitterPublicReviews' : ActorMethod<
    [Id, bigint],
    Array<
      {
        'clientName' : string,
        'createdAt' : bigint,
        'comment' : [] | [string],
        'rating' : bigint,
      }
    >
  >,
  'getSitterReviews' : ActorMethod<[Id], Array<Public__5>>,
  'getSitterServiceRates' : ActorMethod<[Id], Array<Public__1>>,
  'getSitterStatsById' : ActorMethod<
    [Id],
    {
      'repeatClientCount' : bigint,
      'totalEarningsCents' : bigint,
      'currentMonthEarningsCents' : bigint,
      'repeatClientRatePct' : number,
      'totalCompletedBookings' : bigint,
      'adHocJobCount' : bigint,
    }
  >,
  'getSittersForSelection' : ActorMethod<
    [string],
    Array<
      {
        'id' : bigint,
        'bio' : string,
        'owner' : [] | [Principal],
        'serviceRadius' : [] | [bigint],
        'birthdate' : [] | [bigint],
        'name' : string,
        'hourlyRate' : bigint,
        'photoUrl' : string,
        'isAnonymized' : [] | [boolean],
        'isActive' : boolean,
        'serviceZip' : [] | [string],
        'memberSince' : [] | [bigint],
        'bookingsCompleted' : bigint,
        'acceptingNewClients' : [] | [boolean],
        'serviceRates' : Array<{ 'service' : string, 'ratePerHour' : bigint }>,
        'repeatClientRate' : bigint,
        'credentialsChecklist' : {
          'isProfessionalMember' : [] | [boolean],
          'hasCertificationOrTraining' : [] | [boolean],
          'hasReferences' : [] | [boolean],
          'hasBusinessLicense' : [] | [boolean],
          'isInsuredAndBonded' : [] | [boolean],
          'usesServiceAgreement' : [] | [boolean],
          'hasBackgroundCheck' : [] | [boolean],
        },
        'rating' : number,
        'reviewCount' : bigint,
        'location' : string,
        'services' : Array<string>,
      }
    >
  >,
  'getSittersNearZip' : ActorMethod<
    [string, bigint],
    Array<
      {
        'id' : bigint,
        'bio' : string,
        'owner' : [] | [Principal],
        'serviceRadius' : [] | [bigint],
        'birthdate' : [] | [bigint],
        'name' : string,
        'hourlyRate' : bigint,
        'photoUrl' : string,
        'isAnonymized' : [] | [boolean],
        'isActive' : boolean,
        'serviceZip' : [] | [string],
        'acceptingNewClients' : [] | [boolean],
        'serviceRates' : Array<{ 'service' : string, 'ratePerHour' : bigint }>,
        'rating' : number,
        'reviewCount' : bigint,
        'location' : string,
        'services' : Array<string>,
      }
    >
  >,
  'getStripeFreePlanPriceId' : ActorMethod<[], string>,
  'getStripePublicConfig' : ActorMethod<
    [],
    { 'isLiveMode' : boolean, 'priceId' : string, 'publishableKey' : string }
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionState' : ActorMethod<[bigint], [] | [SubscriptionRecord]>,
  'getSupportTickets' : ActorMethod<[], Array<Public__4>>,
  'getTeamBookings' : ActorMethod<[string], Array<bigint>>,
  'getTeamById' : ActorMethod<[string], [] | [Team]>,
  'getTeamMessages' : ActorMethod<[string, bigint], Array<TeamMessage>>,
  'getTipsBySitter' : ActorMethod<[Id], Array<Public__3>>,
  'getUnreadNotificationCount' : ActorMethod<[bigint], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminAccess' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'grantSupportAccess' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'handleStripeWebhook' : ActorMethod<[string, string, string], undefined>,
  'hasSupportAccess' : ActorMethod<[Principal], boolean>,
  'initSitterTrial' : ActorMethod<[bigint], undefined>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSitterFrozen' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'leaveTeam' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'markNotificationRead' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'openSupportTicket' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'postServiceLog' : ActorMethod<[Creation], Public__2>,
  /**
   * / Records one API call for the given date string (YYYY-MM-DD).
   * / Resets the daily counter whenever the date changes.
   */
  'recordApiCall' : ActorMethod<[string], undefined>,
  'recordSubscriptionPayment' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordTip' : ActorMethod<
    [Id, Id, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'redeemCoupon' : ActorMethod<
    [string, string],
    { 'ok' : DealOffer } |
      { 'err' : string }
  >,
  'rejectSitterApplication' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resolveSupportTicket' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'respondToInvite' : ActorMethod<
    [string, boolean],
    { 'ok' : Team } |
      { 'err' : string }
  >,
  'revokeAdminAccess' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfile],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'seedBaileyLinneaTeam' : ActorMethod<
    [],
    { 'ok' : Team } |
      { 'err' : string }
  >,
  'seedBaileyLinneaTeamWithIds' : ActorMethod<
    [bigint, bigint],
    { 'ok' : Team } |
      { 'err' : string }
  >,
  'sendBookingConfirmationEmail' : ActorMethod<[Id], undefined>,
  'sendBookingConfirmedEmails' : ActorMethod<[Id], undefined>,
  'sendClientNudgeSitter' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendInvoiceToClient' : ActorMethod<
    [Id],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendPaymentReminder' : ActorMethod<
    [Id],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendRecurringBookingEmails' : ActorMethod<[string], undefined>,
  'sendRecurringGroupConfirmedEmails' : ActorMethod<[string], undefined>,
  'sendServiceCompletionEmail' : ActorMethod<[Id], undefined>,
  'sendTeamMessage' : ActorMethod<
    [string, bigint, string, [] | [bigint]],
    { 'ok' : TeamMessage } |
      { 'err' : string }
  >,
  'setAdminNotificationEmail' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: update the daily and monthly call limits.
   */
  'setApiLimits' : ActorMethod<[bigint, bigint], undefined>,
  'setCallerAsAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'setFreePlanPriceId' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setInvoicePaymentMethod' : ActorMethod<
    [Id, PaymentMethodDetails],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSitterAvailability' : ActorMethod<
    [Id, Array<AvailabilityEntry>],
    undefined
  >,
  'setSitterHandle' : ActorMethod<
    [Id, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSitterPageComponents' : ActorMethod<
    [bigint, PageComponentVisibility],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSitterServiceRates' : ActorMethod<[Id, Array<Public__1>], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setStripeWebhookSecret' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitReview' : ActorMethod<[Id, number, string, Id], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfreezeSitterAccount' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Mark an ad hoc job's payment as paid.
   */
  'updateAdHocJobPayment' : ActorMethod<
    [bigint, string, [] | [PaymentMethodDetails]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBookingStatus' : ActorMethod<
    [
      Id,
      { 'cancelled' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updateCredentialChecklist' : ActorMethod<
    [bigint, CredentialChecklist],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateDutyStatus' : ActorMethod<
    [
      string,
      string,
      { 'assigned' : null } |
        { 'done' : null } |
        { 'inProgress' : null },
    ],
    { 'ok' : DutyAssignment } |
      { 'err' : string }
  >,
  'updateInvoiceAdHocItems' : ActorMethod<
    [Id, Array<AdHocLineItem>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateInvoicePaidDate' : ActorMethod<
    [Id, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePaymentSplits' : ActorMethod<[UpdateSplits], undefined>,
  'updatePaymentWithDiscount' : ActorMethod<
    [Id, bigint, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateServiceCompletion' : ActorMethod<
    [Id, [] | [Time], [] | [bigint], [] | [string], [] | [bigint]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateServiceLogStopTime' : ActorMethod<[UpdateStopTime], undefined>,
  'updateSitterEarningsGoal' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSitterProfile' : ActorMethod<[Update], Public>,
  'updateSitterProfileV2' : ActorMethod<
    [SitterProfileV2Update],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStripeConfig' : ActorMethod<
    [string, string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTaskDone' : ActorMethod<
    [string, string, string, boolean],
    { 'ok' : DutyTask } |
      { 'err' : string }
  >,
  'updateTeamSplits' : ActorMethod<
    [string, Array<[bigint, bigint]>],
    { 'ok' : Team } |
      { 'err' : string }
  >,
  'validateCoupon' : ActorMethod<
    [string],
    { 'ok' : DealOffer } |
      { 'err' : string }
  >,
  'validateRecurringAvailability' : ActorMethod<
    [bigint, Array<Time>, string, string, Array<string>, string],
    Array<OccurrenceAvailability>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];