/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Team = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'dissolved' : IDL.Null }),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberIds' : IDL.Vec(IDL.Nat),
  'teamId' : IDL.Text,
  'splitPercentages' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CoBookingAssignment = IDL.Record({
  'bookingId' : IDL.Nat,
  'assignments' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'teamId' : IDL.Text,
  'splitAmounts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const DutyTask = IDL.Record({
  'doneAt' : IDL.Opt(IDL.Int),
  'done' : IDL.Bool,
  'taskId' : IDL.Text,
  'taskLabel' : IDL.Text,
});
export const DutyAssignment = IDL.Record({
  'status' : IDL.Variant({
    'assigned' : IDL.Null,
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'tasks' : IDL.Vec(DutyTask),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'assignedSitterId' : IDL.Nat,
  'dutyId' : IDL.Text,
});
export const BookingAgreements = IDL.Record({
  'terms' : IDL.Bool,
  'termsVersion' : IDL.Nat,
  'cancellationPolicy' : IDL.Bool,
  'communications' : IDL.Bool,
  'nonEmploymentAck' : IDL.Bool,
  'privacy' : IDL.Bool,
  'callRequest' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'declined' : IDL.Null,
});
export const Time = IDL.Int;
export const ServiceSlot = IDL.Record({
  'service' : IDL.Text,
  'startTime' : IDL.Text,
  'sitterId' : IDL.Nat,
  'endTime' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'ratePerHour' : IDL.Nat,
});
export const DayServiceSchedule = IDL.Record({
  'date' : IDL.Text,
  'slots' : IDL.Vec(ServiceSlot),
});
export const Pet = IDL.Record({
  'petNotes' : IDL.Opt(IDL.Text),
  'petName' : IDL.Text,
  'petType' : IDL.Text,
  'breed' : IDL.Opt(IDL.Text),
});
export const RecurrencePattern = IDL.Variant({
  'monthly' : IDL.Null,
  'biweekly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const AlternativeWindow = IDL.Record({
  'duration' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
});
export const TimeSlot = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
export const DaySchedule = IDL.Record({
  'date' : Time,
  'slots' : IDL.Vec(TimeSlot),
});
export const Public__8 = IDL.Record({
  'id' : Id,
  'tip' : IDL.Opt(IDL.Nat),
  'agreements' : IDL.Opt(BookingAgreements),
  'status' : BookingStatus,
  'paymentSessionId' : IDL.Opt(IDL.Text),
  'endDate' : Time,
  'serviceSchedule' : IDL.Opt(IDL.Vec(DayServiceSchedule)),
  'isRecurring' : IDL.Bool,
  'clientName' : IDL.Text,
  'adHocClientContact' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'pets' : IDL.Vec(Pet),
  'clientEmail' : IDL.Text,
  'recurrencePattern' : IDL.Opt(RecurrencePattern),
  'recurrenceEndDate' : IDL.Opt(Time),
  'alternativeWindows' : IDL.Opt(IDL.Vec(AlternativeWindow)),
  'notes' : IDL.Text,
  'clientPhone' : IDL.Text,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'isAdHoc' : IDL.Bool,
  'schedule' : IDL.Opt(IDL.Vec(DaySchedule)),
  'declineReason' : IDL.Opt(IDL.Text),
  'sitterIds' : IDL.Vec(IDL.Nat),
  'services' : IDL.Vec(IDL.Text),
  'startDate' : Time,
});
export const Creation__3 = IDL.Record({
  'tip' : IDL.Opt(IDL.Nat),
  'agreements' : IDL.Opt(BookingAgreements),
  'endDate' : Time,
  'serviceSchedule' : IDL.Opt(IDL.Vec(DayServiceSchedule)),
  'isRecurring' : IDL.Bool,
  'clientName' : IDL.Text,
  'adHocClientContact' : IDL.Opt(IDL.Text),
  'pets' : IDL.Vec(Pet),
  'clientEmail' : IDL.Text,
  'recurrencePattern' : IDL.Opt(RecurrencePattern),
  'recurrenceEndDate' : IDL.Opt(Time),
  'notes' : IDL.Text,
  'clientPhone' : IDL.Text,
  'isAdHoc' : IDL.Opt(IDL.Bool),
  'schedule' : IDL.Opt(IDL.Vec(DaySchedule)),
  'callRequest' : IDL.Opt(IDL.Bool),
  'sitterIds' : IDL.Vec(IDL.Nat),
  'services' : IDL.Vec(IDL.Text),
  'startDate' : Time,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const DiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percent' : IDL.Null,
});
export const DealOffer = IDL.Record({
  'id' : IDL.Text,
  'redeemedBy' : IDL.Vec(IDL.Text),
  'redeemedCount' : IDL.Nat,
  'couponCode' : IDL.Text,
  'discountValue' : IDL.Float64,
  'sitterId' : IDL.Nat,
  'discountType' : DiscountType,
  'description' : IDL.Text,
  'sentAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'expirationDate' : IDL.Int,
  'maxUses' : IDL.Opt(IDL.Nat),
  'clientEmails' : IDL.Vec(IDL.Text),
});
export const JobThread = IDL.Record({
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
  'bookingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'duties' : IDL.Vec(DutyAssignment),
  'teamId' : IDL.Text,
  'threadId' : IDL.Text,
});
export const NotificationRecord = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'recipientSitterId' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'manual' : IDL.Null,
});
export const PaymentSplit = IDL.Record({
  'sitterId' : Id,
  'paid' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const Creation__2 = IDL.Record({
  'method' : PaymentMethod,
  'bookingId' : Id,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'splits' : IDL.Vec(PaymentSplit),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
});
export const AdHocLineItem = IDL.Record({
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amountCents' : IDL.Int,
});
export const PaymentMethodDetails = IDL.Variant({
  'venmo' : IDL.Record({ 'handle' : IDL.Text }),
  'cash' : IDL.Record({ 'instructions' : IDL.Text }),
  'applePayCash' : IDL.Record({ 'sitterPhone' : IDL.Text }),
});
export const Public__6 = IDL.Record({
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'originalAmount' : IDL.Opt(IDL.Nat),
  'bookingId' : Id,
  'actualEndTime' : IDL.Opt(Time),
  'discountAmount' : IDL.Opt(IDL.Nat),
  'adHocItems' : IDL.Vec(AdHocLineItem),
  'confirmedAt' : IDL.Opt(Time),
  'discountPercent' : IDL.Opt(IDL.Nat),
  'paidDate' : IDL.Opt(IDL.Text),
  'manualConfirmedBy' : IDL.Opt(IDL.Principal),
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'paymentMethodDetails' : IDL.Opt(PaymentMethodDetails),
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'splits' : IDL.Vec(PaymentSplit),
  'completionNotes' : IDL.Opt(IDL.Text),
});
export const ClientInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RecurrenceRule = IDL.Record({
  'occurrenceCount' : IDL.Opt(IDL.Nat),
  'pattern' : RecurrencePattern,
  'endDate' : IDL.Opt(Time),
  'daysOfWeek' : IDL.Vec(IDL.Nat8),
  'startDate' : Time,
});
export const PetInfo = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'notes' : IDL.Text,
  'breed' : IDL.Text,
});
export const RecurringGroupCreation = IDL.Record({
  'agreements' : BookingAgreements,
  'startTime' : IDL.Text,
  'totalCostCents' : IDL.Nat,
  'clientInfo' : ClientInfo,
  'sitterId' : IDL.Nat,
  'endTime' : IDL.Text,
  'serviceDuration' : IDL.Nat,
  'recurrenceRule' : RecurrenceRule,
  'serviceIds' : IDL.Vec(IDL.Text),
  'petInfo' : IDL.Vec(PetInfo),
});
export const GroupStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const BookingGroup = IDL.Record({
  'startTime' : IDL.Text,
  'status' : GroupStatus,
  'clientInfo' : ClientInfo,
  'sitterId' : IDL.Nat,
  'endTime' : IDL.Text,
  'createdAt' : Time,
  'occurrenceIds' : IDL.Vec(IDL.Nat),
  'recurrenceRule' : RecurrenceRule,
  'serviceIds' : IDL.Vec(IDL.Text),
  'groupId' : IDL.Text,
  'petInfo' : IDL.Vec(PetInfo),
});
export const Creation__1 = IDL.Record({
  'bio' : IDL.Text,
  'birthdate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const Public__1 = IDL.Record({
  'service' : IDL.Text,
  'ratePerHour' : IDL.Nat,
});
export const Public = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'birthdate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'isAnonymized' : IDL.Opt(IDL.Bool),
  'isActive' : IDL.Bool,
  'serviceRates' : IDL.Vec(Public__1),
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'location' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const TeamInvite = IDL.Record({
  'status' : IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  }),
  'expiresAt' : IDL.Int,
  'inviteId' : IDL.Text,
  'createdAt' : IDL.Int,
  'toSitterId' : IDL.Opt(IDL.Nat),
  'inviteCode' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Text),
  'fromSitterId' : IDL.Nat,
});
export const SubscriptionRecord = IDL.Record({
  'isFrozen' : IDL.Bool,
  'frozenAt' : IDL.Opt(IDL.Int),
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'trialExpiredEmailSent' : IDL.Opt(IDL.Bool),
  'isFreePlan' : IDL.Opt(IDL.Bool),
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'lastPaymentAt' : IDL.Opt(IDL.Int),
  'isSubscribed' : IDL.Bool,
  'trialReminderSent' : IDL.Opt(IDL.Bool),
  'subscriptionStartedAt' : IDL.Opt(IDL.Int),
  'trialStartedAt' : IDL.Opt(IDL.Int),
});
export const AuditAction = IDL.Variant({
  'SupportTicketOpened' : IDL.Null,
  'AccountFrozen' : IDL.Null,
  'BookingDeleted' : IDL.Null,
  'GdprExportRequested' : IDL.Null,
  'SupportTicketResolved' : IDL.Null,
  'AccountUnfrozen' : IDL.Null,
  'ServiceCompletionUpdated' : IDL.Null,
  'SubscriptionRecorded' : IDL.Null,
  'GdprAnonymizationRequested' : IDL.Null,
  'PriceAdjusted' : IDL.Null,
  'AccountAnonymized' : IDL.Null,
  'ConsentRecorded' : IDL.Null,
  'PaymentDeleted' : IDL.Null,
  'BookingDeclined' : IDL.Null,
  'SubscriptionCancelled' : IDL.Null,
  'DiscountApplied' : IDL.Null,
  'AdminAccessRevoked' : IDL.Null,
  'AdHocJobCreated' : IDL.Null,
  'SitterDeleted' : IDL.Null,
  'GdprExportDownloaded' : IDL.Null,
  'SitterDeactivated' : IDL.Null,
  'SitterReactivated' : IDL.Null,
  'AdminAccessGranted' : IDL.Null,
});
export const Public__7 = IDL.Record({
  'id' : Id,
  'action' : AuditAction,
  'snapshot' : IDL.Text,
  'entityId' : IDL.Nat,
  'timestamp' : Time,
  'entityType' : IDL.Text,
  'deletedBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const TeamMessage = IDL.Record({
  'msgId' : IDL.Text,
  'content' : IDL.Text,
  'msgType' : IDL.Variant({ 'channel' : IDL.Null, 'jobThread' : IDL.Null }),
  'threadBookingId' : IDL.Opt(IDL.Nat),
  'senderSitterId' : IDL.Nat,
  'sentAt' : IDL.Int,
  'teamId' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'senderId' : IDL.Opt(IDL.Principal),
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'adminAccessing' : IDL.Null,
  'open' : IDL.Null,
});
export const Public__4 = IDL.Record({
  'id' : IDL.Text,
  'status' : TicketStatus,
  'sitterId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'accessRevokedAt' : IDL.Opt(IDL.Int),
  'accessGrantedAt' : IDL.Opt(IDL.Int),
  'issue' : IDL.Text,
  'adminNotes' : IDL.Opt(IDL.Text),
  'sitterName' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const Public__5 = IDL.Record({
  'bookingId' : IDL.Nat,
  'createdAt' : Time,
  'reviewText' : IDL.Text,
  'rating' : IDL.Float64,
});
export const ServiceStatus = IDL.Variant({
  'completed' : IDL.Null,
  'checkedIn' : IDL.Null,
  'issueReported' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Public__2 = IDL.Record({
  'id' : Id,
  'startTime' : IDL.Opt(Time),
  'status' : ServiceStatus,
  'bookingId' : Id,
  'sitterId' : Id,
  'createdAt' : Time,
  'stopTime' : IDL.Opt(Time),
  'notes' : IDL.Text,
});
export const AvailabilityEntry = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
});
export const SitterBookingStats = IDL.Record({
  'completedVisits' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'uniqueClients' : IDL.Nat,
  'repeatClients' : IDL.Nat,
});
export const CRMClient = IDL.Record({
  'clientName' : IDL.Text,
  'lastBookingDate' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'clientEmail' : IDL.Text,
  'totalSpent' : IDL.Float64,
  'clientPhone' : IDL.Text,
  'bookingCount' : IDL.Nat,
});
export const CredentialChecklist = IDL.Record({
  'isProfessionalMember' : IDL.Opt(IDL.Bool),
  'hasCertificationOrTraining' : IDL.Opt(IDL.Bool),
  'hasReferences' : IDL.Opt(IDL.Bool),
  'hasBusinessLicense' : IDL.Opt(IDL.Bool),
  'isInsuredAndBonded' : IDL.Opt(IDL.Bool),
  'usesServiceAgreement' : IDL.Opt(IDL.Bool),
  'hasBackgroundCheck' : IDL.Opt(IDL.Bool),
});
export const PageComponentVisibility = IDL.Record({
  'showAvailability' : IDL.Bool,
  'showCredentials' : IDL.Bool,
  'showResponseTime' : IDL.Bool,
  'showCertifications' : IDL.Bool,
  'showPetTypes' : IDL.Bool,
  'showStats' : IDL.Bool,
  'showGallery' : IDL.Bool,
  'showPromo' : IDL.Bool,
  'showReviews' : IDL.Bool,
  'showRepeatClients' : IDL.Bool,
});
export const SitterPublicV2Extension = IDL.Record({
  'pageComponents' : IDL.Opt(PageComponentVisibility),
  'serviceRadius' : IDL.Opt(IDL.Nat),
  'serviceZip' : IDL.Opt(IDL.Text),
  'acceptingNewClients' : IDL.Opt(IDL.Bool),
  'bannerUrl' : IDL.Opt(IDL.Text),
  'certificationsList' : IDL.Opt(IDL.Vec(IDL.Text)),
  'responseTime' : IDL.Opt(IDL.Text),
  'petTypesServed' : IDL.Opt(IDL.Vec(IDL.Text)),
  'credentialChecklist' : IDL.Opt(CredentialChecklist),
  'pinnedPromoOfferId' : IDL.Opt(IDL.Text),
  'galleryPhotos' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const SitterLicenseStatus = IDL.Record({
  'trialDaysRemaining' : IDL.Opt(IDL.Nat),
  'trialActive' : IDL.Bool,
  'isFrozen' : IDL.Bool,
  'isGrandfathered' : IDL.Bool,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'subscriptionStatus' : IDL.Text,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'isSubscribed' : IDL.Bool,
  'isLicensed' : IDL.Bool,
  'trialStartedAt' : IDL.Opt(IDL.Int),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Public__3 = IDL.Record({
  'bookingId' : IDL.Nat,
  'sitterId' : IDL.Nat,
  'clientName' : IDL.Text,
  'createdAt' : Time,
  'amountCents' : IDL.Nat,
});
export const Creation = IDL.Record({
  'startTime' : IDL.Opt(Time),
  'status' : ServiceStatus,
  'bookingId' : Id,
  'sitterId' : Id,
  'notes' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateSplits = IDL.Record({
  'bookingId' : Id,
  'splits' : IDL.Vec(PaymentSplit),
});
export const UpdateStopTime = IDL.Record({ 'id' : Id, 'stopTime' : Time });
export const Update = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const SitterProfileV2Update = IDL.Record({
  'sitterId' : IDL.Nat,
  'pageComponents' : IDL.Opt(PageComponentVisibility),
  'serviceRadius' : IDL.Opt(IDL.Nat),
  'serviceZip' : IDL.Opt(IDL.Text),
  'acceptingNewClients' : IDL.Opt(IDL.Bool),
  'bannerUrl' : IDL.Opt(IDL.Text),
  'certificationsList' : IDL.Opt(IDL.Vec(IDL.Text)),
  'responseTime' : IDL.Opt(IDL.Text),
  'petTypesServed' : IDL.Opt(IDL.Vec(IDL.Text)),
  'credentialChecklist' : IDL.Opt(CredentialChecklist),
  'pinnedPromoOfferId' : IDL.Opt(IDL.Text),
  'galleryPhotos' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const OccurrenceAvailability = IDL.Record({
  'date' : Time,
  'available' : IDL.Bool,
  'conflictReason' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptInviteByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
      [],
    ),
  'addMessage' : IDL.Func([Id, IDL.Text, IDL.Text], [], []),
  'addPhotoConsentLog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adjustPaymentPrice' : IDL.Func(
      [Id, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAnonymizeSitter' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminExportSitterData' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'anonymizeSitterAccount' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveSitterApplication' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCoSitters' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      [IDL.Variant({ 'ok' : CoBookingAssignment, 'err' : IDL.Text })],
      [],
    ),
  'assignDuty' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : DutyAssignment, 'err' : IDL.Text })],
      [],
    ),
  'assignSitterToFreePlan' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'backfillSitterHandles' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'cancelBookingByClient' : IDL.Func(
      [Id, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelRecurringGroup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelSubscription' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'checkAndSendTrialReminder' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'checkSittersAvailabilityForRebook' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [
        IDL.Vec(
          IDL.Record({
            'sitterId' : IDL.Nat,
            'available' : IDL.Bool,
            'reason' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'clearAllData' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmManualPayment' : IDL.Func([Id], [], []),
  'confirmManualPaymentWithEmail' : IDL.Func(
      [Id, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'confirmRecurringGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmRecurringOccurrence' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmStripeCheckoutSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createAdHocJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : Public__8, 'err' : IDL.Text })],
      [],
    ),
  'createBooking' : IDL.Func([Creation__3], [Public__8], []),
  'createBookingWithCoupon' : IDL.Func(
      [Creation__3, IDL.Opt(IDL.Text)],
      [Public__8],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDealOffer' : IDL.Func(
      [
        IDL.Nat,
        DiscountType,
        IDL.Float64,
        IDL.Text,
        IDL.Int,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
      [],
    ),
  'createJobThread' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : JobThread, 'err' : IDL.Text })],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [NotificationRecord],
      [],
    ),
  'createPayment' : IDL.Func([Creation__2], [Public__6], []),
  'createRecurringBookingGroup' : IDL.Func(
      [RecurringGroupCreation],
      [IDL.Variant({ 'ok' : BookingGroup, 'err' : IDL.Text })],
      [],
    ),
  'createSitterProfile' : IDL.Func([Creation__1], [Public], []),
  'createSubscriptionCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTeamInvite' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Variant({ 'ok' : TeamInvite, 'err' : IDL.Text })],
      [],
    ),
  'declineBookingRequest' : IDL.Func(
      [Id, IDL.Text, IDL.Vec(AlternativeWindow)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'declineRecurringOccurrence' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(
          IDL.Record({
            'duration' : IDL.Text,
            'date' : IDL.Text,
            'time' : IDL.Text,
          })
        ),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBooking' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deletePayment' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteSitterProfile' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'dissolveTeamAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'exportSitterData' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'fixSitterZipCodes' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'freezeSitterAccount' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateTeamInviteLink' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getActiveSitters' : IDL.Func([], [IDL.Vec(Public)], ['query']),
  'getAdHocJobsBySitter' : IDL.Func([IDL.Nat], [IDL.Vec(Public__8)], ['query']),
  'getAdminBookingAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'serviceTypeDurations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          'serviceTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'avgServiceDurationMinutes' : IDL.Float64,
          'avgTimeToPaymentMinutes' : IDL.Float64,
          'serviceTypeRevenue' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getAdminBookingStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingCount' : IDL.Nat,
          'cancelledCount' : IDL.Nat,
          'completedCount' : IDL.Nat,
          'confirmedCount' : IDL.Nat,
          'pendingRevenue' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'confirmedRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAdminNotificationEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminPendingRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdminPendingRevenueBreakdown' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'bookingId' : IDL.Nat,
            'clientName' : IDL.Text,
            'amount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Public__8)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Public__6)], ['query']),
  'getAllSitterHandles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllSitters' : IDL.Func([], [IDL.Vec(Public)], ['query']),
  'getAllSubscriptionStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, SubscriptionRecord))],
      ['query'],
    ),
  'getAllTeamsAdmin' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getApiUsageLimits' : IDL.Func(
      [],
      [
        IDL.Record({
          'monthlyCount' : IDL.Nat,
          'monthlyLimit' : IDL.Nat,
          'dailyCount' : IDL.Nat,
          'dailyLimit' : IDL.Nat,
          'resetDate' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAuditLog' : IDL.Func([], [IDL.Vec(Public__7)], ['query']),
  'getAvailableHourlyWindows' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'startTime' : IDL.Text,
            'availableSitterCount' : IDL.Nat,
            'endTime' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAvailableSittersForWindow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Public)],
      ['query'],
    ),
  'getBookingHeatmapData' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'pendingCount' : IDL.Nat,
            'sitterId' : IDL.Nat,
            'date' : IDL.Text,
            'hour' : IDL.Nat,
            'confirmedCount' : IDL.Nat,
            'sitterName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getBookingsByClientEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Public__8)],
      ['query'],
    ),
  'getBookingsByClientPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Public__8)],
      ['query'],
    ),
  'getBookingsBySitter' : IDL.Func([Id], [IDL.Vec(Public__8)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoBookingAssignment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CoBookingAssignment)],
      ['query'],
    ),
  'getCompletedBookingsByContact' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Public__8)],
      ['query'],
    ),
  'getCompletedBookingsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getDealOffersBySitter' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DealOffer)],
      ['query'],
    ),
  'getGrantedAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getJobThread' : IDL.Func([IDL.Nat], [IDL.Opt(JobThread)], ['query']),
  'getJobThreadMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TeamMessage)],
      ['query'],
    ),
  'getJobThreadsForTeam' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobThread)],
      ['query'],
    ),
  'getMessages' : IDL.Func([Id], [IDL.Vec(Message)], ['query']),
  'getMySupportTickets' : IDL.Func([], [IDL.Vec(Public__4)], ['query']),
  'getMyTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getNotificationsBySitter' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(NotificationRecord)],
      ['query'],
    ),
  'getPayment' : IDL.Func([Id], [IDL.Opt(Public__6)], ['query']),
  'getPaymentAuditLog' : IDL.Func([Id], [IDL.Vec(Public__7)], ['query']),
  'getPaymentsByBookingIds' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(Public__6)],
      ['query'],
    ),
  'getPendingInvitesForSitter' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TeamInvite)],
      ['query'],
    ),
  'getPublicSitterProfile' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Nat,
            'bio' : IDL.Opt(IDL.Text),
            'reviews' : IDL.Vec(
              IDL.Record({
                'clientName' : IDL.Text,
                'createdAt' : IDL.Int,
                'comment' : IDL.Opt(IDL.Text),
                'rating' : IDL.Nat,
              })
            ),
            'name' : IDL.Text,
            'badges' : IDL.Vec(IDL.Text),
            'isActive' : IDL.Bool,
            'averageRating' : IDL.Float64,
            'profilePhotoUrl' : IDL.Opt(IDL.Text),
            'reviewCount' : IDL.Nat,
            'services' : IDL.Vec(
              IDL.Record({
                'serviceName' : IDL.Text,
                'duration' : IDL.Opt(IDL.Text),
                'price' : IDL.Float64,
              })
            ),
          })
        ),
      ],
      ['query'],
    ),
  'getRecurringGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BookingGroup)],
      ['query'],
    ),
  'getRecurringGroupsByClient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingGroup)],
      ['query'],
    ),
  'getRecurringGroupsBySitter' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BookingGroup)],
      ['query'],
    ),
  'getReviewsBySitter' : IDL.Func([Id], [IDL.Vec(Public__5)], ['query']),
  'getServiceLogsByBooking' : IDL.Func([Id], [IDL.Vec(Public__2)], ['query']),
  'getSitterAvailability' : IDL.Func(
      [Id],
      [IDL.Vec(AvailabilityEntry)],
      ['query'],
    ),
  'getSitterBookingStats' : IDL.Func(
      [IDL.Nat],
      [SitterBookingStats],
      ['query'],
    ),
  'getSitterClientsForCRM' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CRMClient)],
      ['query'],
    ),
  'getSitterCredentials' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CredentialChecklist)],
      ['query'],
    ),
  'getSitterExtendedPublic' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SitterPublicV2Extension)],
      ['query'],
    ),
  'getSitterHandle' : IDL.Func([Id], [IDL.Opt(IDL.Text)], ['query']),
  'getSitterLicenseStatus' : IDL.Func([], [SitterLicenseStatus], ['query']),
  'getSitterPageComponents' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PageComponentVisibility)],
      ['query'],
    ),
  'getSitterPrivateData' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'emergencyContact' : IDL.Opt(IDL.Text),
            'earningsGoal' : IDL.Opt(IDL.Nat),
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getSitterProfile' : IDL.Func([Id], [Public], ['query']),
  'getSitterPublicReviews' : IDL.Func(
      [Id, IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'clientName' : IDL.Text,
            'createdAt' : IDL.Int,
            'comment' : IDL.Opt(IDL.Text),
            'rating' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getSitterReviews' : IDL.Func([Id], [IDL.Vec(Public__5)], ['query']),
  'getSitterServiceRates' : IDL.Func([Id], [IDL.Vec(Public__1)], ['query']),
  'getSitterStatsById' : IDL.Func(
      [Id],
      [
        IDL.Record({
          'repeatClientCount' : IDL.Nat,
          'totalEarningsCents' : IDL.Nat,
          'currentMonthEarningsCents' : IDL.Nat,
          'repeatClientRatePct' : IDL.Float64,
          'totalCompletedBookings' : IDL.Nat,
          'adHocJobCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSittersForSelection' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'bio' : IDL.Text,
            'owner' : IDL.Opt(IDL.Principal),
            'serviceRadius' : IDL.Opt(IDL.Nat),
            'birthdate' : IDL.Opt(IDL.Int),
            'name' : IDL.Text,
            'hourlyRate' : IDL.Nat,
            'photoUrl' : IDL.Text,
            'isAnonymized' : IDL.Opt(IDL.Bool),
            'isActive' : IDL.Bool,
            'serviceZip' : IDL.Opt(IDL.Text),
            'memberSince' : IDL.Opt(IDL.Int),
            'bookingsCompleted' : IDL.Nat,
            'acceptingNewClients' : IDL.Opt(IDL.Bool),
            'serviceRates' : IDL.Vec(
              IDL.Record({ 'service' : IDL.Text, 'ratePerHour' : IDL.Nat })
            ),
            'repeatClientRate' : IDL.Nat,
            'credentialsChecklist' : IDL.Record({
              'isProfessionalMember' : IDL.Opt(IDL.Bool),
              'hasCertificationOrTraining' : IDL.Opt(IDL.Bool),
              'hasReferences' : IDL.Opt(IDL.Bool),
              'hasBusinessLicense' : IDL.Opt(IDL.Bool),
              'isInsuredAndBonded' : IDL.Opt(IDL.Bool),
              'usesServiceAgreement' : IDL.Opt(IDL.Bool),
              'hasBackgroundCheck' : IDL.Opt(IDL.Bool),
            }),
            'rating' : IDL.Float64,
            'reviewCount' : IDL.Nat,
            'location' : IDL.Text,
            'services' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getSittersNearZip' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'bio' : IDL.Text,
            'owner' : IDL.Opt(IDL.Principal),
            'serviceRadius' : IDL.Opt(IDL.Nat),
            'birthdate' : IDL.Opt(IDL.Int),
            'name' : IDL.Text,
            'hourlyRate' : IDL.Nat,
            'photoUrl' : IDL.Text,
            'isAnonymized' : IDL.Opt(IDL.Bool),
            'isActive' : IDL.Bool,
            'serviceZip' : IDL.Opt(IDL.Text),
            'acceptingNewClients' : IDL.Opt(IDL.Bool),
            'serviceRates' : IDL.Vec(
              IDL.Record({ 'service' : IDL.Text, 'ratePerHour' : IDL.Nat })
            ),
            'rating' : IDL.Float64,
            'reviewCount' : IDL.Nat,
            'location' : IDL.Text,
            'services' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getStripeFreePlanPriceId' : IDL.Func([], [IDL.Text], ['query']),
  'getStripePublicConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'isLiveMode' : IDL.Bool,
          'priceId' : IDL.Text,
          'publishableKey' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionState' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SubscriptionRecord)],
      ['query'],
    ),
  'getSupportTickets' : IDL.Func([], [IDL.Vec(Public__4)], ['query']),
  'getTeamBookings' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getTeamById' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
  'getTeamMessages' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(TeamMessage)],
      ['query'],
    ),
  'getTipsBySitter' : IDL.Func([Id], [IDL.Vec(Public__3)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminAccess' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'grantSupportAccess' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'handleStripeWebhook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'hasSupportAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'initSitterTrial' : IDL.Func([IDL.Nat], [], []),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSitterFrozen' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveTeam' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationRead' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'openSupportTicket' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'postServiceLog' : IDL.Func([Creation], [Public__2], []),
  'recordApiCall' : IDL.Func([IDL.Text], [], []),
  'recordSubscriptionPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordTip' : IDL.Func(
      [Id, Id, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'redeemCoupon' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
      [],
    ),
  'rejectSitterApplication' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resolveSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'respondToInvite' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
      [],
    ),
  'revokeAdminAccess' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfile],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'seedBaileyLinneaTeam' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
      [],
    ),
  'seedBaileyLinneaTeamWithIds' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
      [],
    ),
  'sendBookingConfirmationEmail' : IDL.Func([Id], [], []),
  'sendBookingConfirmedEmails' : IDL.Func([Id], [], []),
  'sendClientNudgeSitter' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendInvoiceToClient' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendPaymentReminder' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendRecurringBookingEmails' : IDL.Func([IDL.Text], [], []),
  'sendRecurringGroupConfirmedEmails' : IDL.Func([IDL.Text], [], []),
  'sendServiceCompletionEmail' : IDL.Func([Id], [], []),
  'sendTeamMessage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : TeamMessage, 'err' : IDL.Text })],
      [],
    ),
  'setAdminNotificationEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setApiLimits' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setCallerAsAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setFreePlanPriceId' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setInvoicePaymentMethod' : IDL.Func(
      [Id, PaymentMethodDetails],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSitterAvailability' : IDL.Func([Id, IDL.Vec(AvailabilityEntry)], [], []),
  'setSitterHandle' : IDL.Func(
      [Id, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSitterPageComponents' : IDL.Func(
      [IDL.Nat, PageComponentVisibility],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSitterServiceRates' : IDL.Func([Id, IDL.Vec(Public__1)], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setStripeWebhookSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitReview' : IDL.Func([Id, IDL.Float64, IDL.Text, Id], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfreezeSitterAccount' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAdHocJobPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(PaymentMethodDetails)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateBookingStatus' : IDL.Func(
      [
        Id,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateCredentialChecklist' : IDL.Func(
      [IDL.Nat, CredentialChecklist],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateDutyStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'assigned' : IDL.Null,
          'done' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [IDL.Variant({ 'ok' : DutyAssignment, 'err' : IDL.Text })],
      [],
    ),
  'updateInvoiceAdHocItems' : IDL.Func(
      [Id, IDL.Vec(AdHocLineItem)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateInvoicePaidDate' : IDL.Func(
      [Id, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePaymentSplits' : IDL.Func([UpdateSplits], [], []),
  'updatePaymentWithDiscount' : IDL.Func(
      [Id, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateServiceCompletion' : IDL.Func(
      [
        Id,
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateServiceLogStopTime' : IDL.Func([UpdateStopTime], [], []),
  'updateSitterEarningsGoal' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSitterProfile' : IDL.Func([Update], [Public], []),
  'updateSitterProfileV2' : IDL.Func(
      [SitterProfileV2Update],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStripeConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTaskDone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : DutyTask, 'err' : IDL.Text })],
      [],
    ),
  'updateTeamSplits' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
      [],
    ),
  'validateCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
      ['query'],
    ),
  'validateRecurringAvailability' : IDL.Func(
      [IDL.Nat, IDL.Vec(Time), IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Vec(OccurrenceAvailability)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Team = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'dissolved' : IDL.Null }),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberIds' : IDL.Vec(IDL.Nat),
    'teamId' : IDL.Text,
    'splitPercentages' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CoBookingAssignment = IDL.Record({
    'bookingId' : IDL.Nat,
    'assignments' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'teamId' : IDL.Text,
    'splitAmounts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const DutyTask = IDL.Record({
    'doneAt' : IDL.Opt(IDL.Int),
    'done' : IDL.Bool,
    'taskId' : IDL.Text,
    'taskLabel' : IDL.Text,
  });
  const DutyAssignment = IDL.Record({
    'status' : IDL.Variant({
      'assigned' : IDL.Null,
      'done' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'tasks' : IDL.Vec(DutyTask),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'assignedSitterId' : IDL.Nat,
    'dutyId' : IDL.Text,
  });
  const BookingAgreements = IDL.Record({
    'terms' : IDL.Bool,
    'termsVersion' : IDL.Nat,
    'cancellationPolicy' : IDL.Bool,
    'communications' : IDL.Bool,
    'nonEmploymentAck' : IDL.Bool,
    'privacy' : IDL.Bool,
    'callRequest' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Time = IDL.Int;
  const ServiceSlot = IDL.Record({
    'service' : IDL.Text,
    'startTime' : IDL.Text,
    'sitterId' : IDL.Nat,
    'endTime' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'ratePerHour' : IDL.Nat,
  });
  const DayServiceSchedule = IDL.Record({
    'date' : IDL.Text,
    'slots' : IDL.Vec(ServiceSlot),
  });
  const Pet = IDL.Record({
    'petNotes' : IDL.Opt(IDL.Text),
    'petName' : IDL.Text,
    'petType' : IDL.Text,
    'breed' : IDL.Opt(IDL.Text),
  });
  const RecurrencePattern = IDL.Variant({
    'monthly' : IDL.Null,
    'biweekly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const AlternativeWindow = IDL.Record({
    'duration' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
  });
  const TimeSlot = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
  const DaySchedule = IDL.Record({
    'date' : Time,
    'slots' : IDL.Vec(TimeSlot),
  });
  const Public__8 = IDL.Record({
    'id' : Id,
    'tip' : IDL.Opt(IDL.Nat),
    'agreements' : IDL.Opt(BookingAgreements),
    'status' : BookingStatus,
    'paymentSessionId' : IDL.Opt(IDL.Text),
    'endDate' : Time,
    'serviceSchedule' : IDL.Opt(IDL.Vec(DayServiceSchedule)),
    'isRecurring' : IDL.Bool,
    'clientName' : IDL.Text,
    'adHocClientContact' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'pets' : IDL.Vec(Pet),
    'clientEmail' : IDL.Text,
    'recurrencePattern' : IDL.Opt(RecurrencePattern),
    'recurrenceEndDate' : IDL.Opt(Time),
    'alternativeWindows' : IDL.Opt(IDL.Vec(AlternativeWindow)),
    'notes' : IDL.Text,
    'clientPhone' : IDL.Text,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'isAdHoc' : IDL.Bool,
    'schedule' : IDL.Opt(IDL.Vec(DaySchedule)),
    'declineReason' : IDL.Opt(IDL.Text),
    'sitterIds' : IDL.Vec(IDL.Nat),
    'services' : IDL.Vec(IDL.Text),
    'startDate' : Time,
  });
  const Creation__3 = IDL.Record({
    'tip' : IDL.Opt(IDL.Nat),
    'agreements' : IDL.Opt(BookingAgreements),
    'endDate' : Time,
    'serviceSchedule' : IDL.Opt(IDL.Vec(DayServiceSchedule)),
    'isRecurring' : IDL.Bool,
    'clientName' : IDL.Text,
    'adHocClientContact' : IDL.Opt(IDL.Text),
    'pets' : IDL.Vec(Pet),
    'clientEmail' : IDL.Text,
    'recurrencePattern' : IDL.Opt(RecurrencePattern),
    'recurrenceEndDate' : IDL.Opt(Time),
    'notes' : IDL.Text,
    'clientPhone' : IDL.Text,
    'isAdHoc' : IDL.Opt(IDL.Bool),
    'schedule' : IDL.Opt(IDL.Vec(DaySchedule)),
    'callRequest' : IDL.Opt(IDL.Bool),
    'sitterIds' : IDL.Vec(IDL.Nat),
    'services' : IDL.Vec(IDL.Text),
    'startDate' : Time,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const DiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percent' : IDL.Null,
  });
  const DealOffer = IDL.Record({
    'id' : IDL.Text,
    'redeemedBy' : IDL.Vec(IDL.Text),
    'redeemedCount' : IDL.Nat,
    'couponCode' : IDL.Text,
    'discountValue' : IDL.Float64,
    'sitterId' : IDL.Nat,
    'discountType' : DiscountType,
    'description' : IDL.Text,
    'sentAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'expirationDate' : IDL.Int,
    'maxUses' : IDL.Opt(IDL.Nat),
    'clientEmails' : IDL.Vec(IDL.Text),
  });
  const JobThread = IDL.Record({
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
    'bookingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'duties' : IDL.Vec(DutyAssignment),
    'teamId' : IDL.Text,
    'threadId' : IDL.Text,
  });
  const NotificationRecord = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'recipientSitterId' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'manual' : IDL.Null,
  });
  const PaymentSplit = IDL.Record({
    'sitterId' : Id,
    'paid' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const Creation__2 = IDL.Record({
    'method' : PaymentMethod,
    'bookingId' : Id,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'splits' : IDL.Vec(PaymentSplit),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const AdHocLineItem = IDL.Record({
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amountCents' : IDL.Int,
  });
  const PaymentMethodDetails = IDL.Variant({
    'venmo' : IDL.Record({ 'handle' : IDL.Text }),
    'cash' : IDL.Record({ 'instructions' : IDL.Text }),
    'applePayCash' : IDL.Record({ 'sitterPhone' : IDL.Text }),
  });
  const Public__6 = IDL.Record({
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'originalAmount' : IDL.Opt(IDL.Nat),
    'bookingId' : Id,
    'actualEndTime' : IDL.Opt(Time),
    'discountAmount' : IDL.Opt(IDL.Nat),
    'adHocItems' : IDL.Vec(AdHocLineItem),
    'confirmedAt' : IDL.Opt(Time),
    'discountPercent' : IDL.Opt(IDL.Nat),
    'paidDate' : IDL.Opt(IDL.Text),
    'manualConfirmedBy' : IDL.Opt(IDL.Principal),
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'paymentMethodDetails' : IDL.Opt(PaymentMethodDetails),
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'splits' : IDL.Vec(PaymentSplit),
    'completionNotes' : IDL.Opt(IDL.Text),
  });
  const ClientInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RecurrenceRule = IDL.Record({
    'occurrenceCount' : IDL.Opt(IDL.Nat),
    'pattern' : RecurrencePattern,
    'endDate' : IDL.Opt(Time),
    'daysOfWeek' : IDL.Vec(IDL.Nat8),
    'startDate' : Time,
  });
  const PetInfo = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'notes' : IDL.Text,
    'breed' : IDL.Text,
  });
  const RecurringGroupCreation = IDL.Record({
    'agreements' : BookingAgreements,
    'startTime' : IDL.Text,
    'totalCostCents' : IDL.Nat,
    'clientInfo' : ClientInfo,
    'sitterId' : IDL.Nat,
    'endTime' : IDL.Text,
    'serviceDuration' : IDL.Nat,
    'recurrenceRule' : RecurrenceRule,
    'serviceIds' : IDL.Vec(IDL.Text),
    'petInfo' : IDL.Vec(PetInfo),
  });
  const GroupStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const BookingGroup = IDL.Record({
    'startTime' : IDL.Text,
    'status' : GroupStatus,
    'clientInfo' : ClientInfo,
    'sitterId' : IDL.Nat,
    'endTime' : IDL.Text,
    'createdAt' : Time,
    'occurrenceIds' : IDL.Vec(IDL.Nat),
    'recurrenceRule' : RecurrenceRule,
    'serviceIds' : IDL.Vec(IDL.Text),
    'groupId' : IDL.Text,
    'petInfo' : IDL.Vec(PetInfo),
  });
  const Creation__1 = IDL.Record({
    'bio' : IDL.Text,
    'birthdate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const Public__1 = IDL.Record({
    'service' : IDL.Text,
    'ratePerHour' : IDL.Nat,
  });
  const Public = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'birthdate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'isAnonymized' : IDL.Opt(IDL.Bool),
    'isActive' : IDL.Bool,
    'serviceRates' : IDL.Vec(Public__1),
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'location' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const TeamInvite = IDL.Record({
    'status' : IDL.Variant({
      'expired' : IDL.Null,
      'pending' : IDL.Null,
      'accepted' : IDL.Null,
      'declined' : IDL.Null,
    }),
    'expiresAt' : IDL.Int,
    'inviteId' : IDL.Text,
    'createdAt' : IDL.Int,
    'toSitterId' : IDL.Opt(IDL.Nat),
    'inviteCode' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Text),
    'fromSitterId' : IDL.Nat,
  });
  const SubscriptionRecord = IDL.Record({
    'isFrozen' : IDL.Bool,
    'frozenAt' : IDL.Opt(IDL.Int),
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'trialExpiredEmailSent' : IDL.Opt(IDL.Bool),
    'isFreePlan' : IDL.Opt(IDL.Bool),
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'lastPaymentAt' : IDL.Opt(IDL.Int),
    'isSubscribed' : IDL.Bool,
    'trialReminderSent' : IDL.Opt(IDL.Bool),
    'subscriptionStartedAt' : IDL.Opt(IDL.Int),
    'trialStartedAt' : IDL.Opt(IDL.Int),
  });
  const AuditAction = IDL.Variant({
    'SupportTicketOpened' : IDL.Null,
    'AccountFrozen' : IDL.Null,
    'BookingDeleted' : IDL.Null,
    'GdprExportRequested' : IDL.Null,
    'SupportTicketResolved' : IDL.Null,
    'AccountUnfrozen' : IDL.Null,
    'ServiceCompletionUpdated' : IDL.Null,
    'SubscriptionRecorded' : IDL.Null,
    'GdprAnonymizationRequested' : IDL.Null,
    'PriceAdjusted' : IDL.Null,
    'AccountAnonymized' : IDL.Null,
    'ConsentRecorded' : IDL.Null,
    'PaymentDeleted' : IDL.Null,
    'BookingDeclined' : IDL.Null,
    'SubscriptionCancelled' : IDL.Null,
    'DiscountApplied' : IDL.Null,
    'AdminAccessRevoked' : IDL.Null,
    'AdHocJobCreated' : IDL.Null,
    'SitterDeleted' : IDL.Null,
    'GdprExportDownloaded' : IDL.Null,
    'SitterDeactivated' : IDL.Null,
    'SitterReactivated' : IDL.Null,
    'AdminAccessGranted' : IDL.Null,
  });
  const Public__7 = IDL.Record({
    'id' : Id,
    'action' : AuditAction,
    'snapshot' : IDL.Text,
    'entityId' : IDL.Nat,
    'timestamp' : Time,
    'entityType' : IDL.Text,
    'deletedBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const TeamMessage = IDL.Record({
    'msgId' : IDL.Text,
    'content' : IDL.Text,
    'msgType' : IDL.Variant({ 'channel' : IDL.Null, 'jobThread' : IDL.Null }),
    'threadBookingId' : IDL.Opt(IDL.Nat),
    'senderSitterId' : IDL.Nat,
    'sentAt' : IDL.Int,
    'teamId' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'senderId' : IDL.Opt(IDL.Principal),
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'adminAccessing' : IDL.Null,
    'open' : IDL.Null,
  });
  const Public__4 = IDL.Record({
    'id' : IDL.Text,
    'status' : TicketStatus,
    'sitterId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'accessRevokedAt' : IDL.Opt(IDL.Int),
    'accessGrantedAt' : IDL.Opt(IDL.Int),
    'issue' : IDL.Text,
    'adminNotes' : IDL.Opt(IDL.Text),
    'sitterName' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const Public__5 = IDL.Record({
    'bookingId' : IDL.Nat,
    'createdAt' : Time,
    'reviewText' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const ServiceStatus = IDL.Variant({
    'completed' : IDL.Null,
    'checkedIn' : IDL.Null,
    'issueReported' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Public__2 = IDL.Record({
    'id' : Id,
    'startTime' : IDL.Opt(Time),
    'status' : ServiceStatus,
    'bookingId' : Id,
    'sitterId' : Id,
    'createdAt' : Time,
    'stopTime' : IDL.Opt(Time),
    'notes' : IDL.Text,
  });
  const AvailabilityEntry = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
  });
  const SitterBookingStats = IDL.Record({
    'completedVisits' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'uniqueClients' : IDL.Nat,
    'repeatClients' : IDL.Nat,
  });
  const CRMClient = IDL.Record({
    'clientName' : IDL.Text,
    'lastBookingDate' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'clientEmail' : IDL.Text,
    'totalSpent' : IDL.Float64,
    'clientPhone' : IDL.Text,
    'bookingCount' : IDL.Nat,
  });
  const CredentialChecklist = IDL.Record({
    'isProfessionalMember' : IDL.Opt(IDL.Bool),
    'hasCertificationOrTraining' : IDL.Opt(IDL.Bool),
    'hasReferences' : IDL.Opt(IDL.Bool),
    'hasBusinessLicense' : IDL.Opt(IDL.Bool),
    'isInsuredAndBonded' : IDL.Opt(IDL.Bool),
    'usesServiceAgreement' : IDL.Opt(IDL.Bool),
    'hasBackgroundCheck' : IDL.Opt(IDL.Bool),
  });
  const PageComponentVisibility = IDL.Record({
    'showAvailability' : IDL.Bool,
    'showCredentials' : IDL.Bool,
    'showResponseTime' : IDL.Bool,
    'showCertifications' : IDL.Bool,
    'showPetTypes' : IDL.Bool,
    'showStats' : IDL.Bool,
    'showGallery' : IDL.Bool,
    'showPromo' : IDL.Bool,
    'showReviews' : IDL.Bool,
    'showRepeatClients' : IDL.Bool,
  });
  const SitterPublicV2Extension = IDL.Record({
    'pageComponents' : IDL.Opt(PageComponentVisibility),
    'serviceRadius' : IDL.Opt(IDL.Nat),
    'serviceZip' : IDL.Opt(IDL.Text),
    'acceptingNewClients' : IDL.Opt(IDL.Bool),
    'bannerUrl' : IDL.Opt(IDL.Text),
    'certificationsList' : IDL.Opt(IDL.Vec(IDL.Text)),
    'responseTime' : IDL.Opt(IDL.Text),
    'petTypesServed' : IDL.Opt(IDL.Vec(IDL.Text)),
    'credentialChecklist' : IDL.Opt(CredentialChecklist),
    'pinnedPromoOfferId' : IDL.Opt(IDL.Text),
    'galleryPhotos' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const SitterLicenseStatus = IDL.Record({
    'trialDaysRemaining' : IDL.Opt(IDL.Nat),
    'trialActive' : IDL.Bool,
    'isFrozen' : IDL.Bool,
    'isGrandfathered' : IDL.Bool,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'subscriptionStatus' : IDL.Text,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'isSubscribed' : IDL.Bool,
    'isLicensed' : IDL.Bool,
    'trialStartedAt' : IDL.Opt(IDL.Int),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Public__3 = IDL.Record({
    'bookingId' : IDL.Nat,
    'sitterId' : IDL.Nat,
    'clientName' : IDL.Text,
    'createdAt' : Time,
    'amountCents' : IDL.Nat,
  });
  const Creation = IDL.Record({
    'startTime' : IDL.Opt(Time),
    'status' : ServiceStatus,
    'bookingId' : Id,
    'sitterId' : Id,
    'notes' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateSplits = IDL.Record({
    'bookingId' : Id,
    'splits' : IDL.Vec(PaymentSplit),
  });
  const UpdateStopTime = IDL.Record({ 'id' : Id, 'stopTime' : Time });
  const Update = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const SitterProfileV2Update = IDL.Record({
    'sitterId' : IDL.Nat,
    'pageComponents' : IDL.Opt(PageComponentVisibility),
    'serviceRadius' : IDL.Opt(IDL.Nat),
    'serviceZip' : IDL.Opt(IDL.Text),
    'acceptingNewClients' : IDL.Opt(IDL.Bool),
    'bannerUrl' : IDL.Opt(IDL.Text),
    'certificationsList' : IDL.Opt(IDL.Vec(IDL.Text)),
    'responseTime' : IDL.Opt(IDL.Text),
    'petTypesServed' : IDL.Opt(IDL.Vec(IDL.Text)),
    'credentialChecklist' : IDL.Opt(CredentialChecklist),
    'pinnedPromoOfferId' : IDL.Opt(IDL.Text),
    'galleryPhotos' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const OccurrenceAvailability = IDL.Record({
    'date' : Time,
    'available' : IDL.Bool,
    'conflictReason' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptInviteByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
        [],
      ),
    'addMessage' : IDL.Func([Id, IDL.Text, IDL.Text], [], []),
    'addPhotoConsentLog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adjustPaymentPrice' : IDL.Func(
        [Id, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAnonymizeSitter' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminExportSitterData' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'anonymizeSitterAccount' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveSitterApplication' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCoSitters' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        [IDL.Variant({ 'ok' : CoBookingAssignment, 'err' : IDL.Text })],
        [],
      ),
    'assignDuty' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : DutyAssignment, 'err' : IDL.Text })],
        [],
      ),
    'assignSitterToFreePlan' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'backfillSitterHandles' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'cancelBookingByClient' : IDL.Func(
        [Id, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelRecurringGroup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelSubscription' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'checkAndSendTrialReminder' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'checkSittersAvailabilityForRebook' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [
          IDL.Vec(
            IDL.Record({
              'sitterId' : IDL.Nat,
              'available' : IDL.Bool,
              'reason' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'clearAllData' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmManualPayment' : IDL.Func([Id], [], []),
    'confirmManualPaymentWithEmail' : IDL.Func(
        [Id, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'confirmRecurringGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmRecurringOccurrence' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmStripeCheckoutSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createAdHocJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : Public__8, 'err' : IDL.Text })],
        [],
      ),
    'createBooking' : IDL.Func([Creation__3], [Public__8], []),
    'createBookingWithCoupon' : IDL.Func(
        [Creation__3, IDL.Opt(IDL.Text)],
        [Public__8],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDealOffer' : IDL.Func(
        [
          IDL.Nat,
          DiscountType,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
        [],
      ),
    'createJobThread' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : JobThread, 'err' : IDL.Text })],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [NotificationRecord],
        [],
      ),
    'createPayment' : IDL.Func([Creation__2], [Public__6], []),
    'createRecurringBookingGroup' : IDL.Func(
        [RecurringGroupCreation],
        [IDL.Variant({ 'ok' : BookingGroup, 'err' : IDL.Text })],
        [],
      ),
    'createSitterProfile' : IDL.Func([Creation__1], [Public], []),
    'createSubscriptionCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTeamInvite' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Variant({ 'ok' : TeamInvite, 'err' : IDL.Text })],
        [],
      ),
    'declineBookingRequest' : IDL.Func(
        [Id, IDL.Text, IDL.Vec(AlternativeWindow)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'declineRecurringOccurrence' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(
            IDL.Record({
              'duration' : IDL.Text,
              'date' : IDL.Text,
              'time' : IDL.Text,
            })
          ),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBooking' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deletePayment' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteSitterProfile' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'dissolveTeamAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'exportSitterData' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'fixSitterZipCodes' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'freezeSitterAccount' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateTeamInviteLink' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getActiveSitters' : IDL.Func([], [IDL.Vec(Public)], ['query']),
    'getAdHocJobsBySitter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Public__8)],
        ['query'],
      ),
    'getAdminBookingAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'serviceTypeDurations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
            'serviceTypeCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'avgServiceDurationMinutes' : IDL.Float64,
            'avgTimeToPaymentMinutes' : IDL.Float64,
            'serviceTypeRevenue' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getAdminBookingStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingCount' : IDL.Nat,
            'cancelledCount' : IDL.Nat,
            'completedCount' : IDL.Nat,
            'confirmedCount' : IDL.Nat,
            'pendingRevenue' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'confirmedRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAdminNotificationEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminPendingRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdminPendingRevenueBreakdown' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'bookingId' : IDL.Nat,
              'clientName' : IDL.Text,
              'amount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Public__8)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Public__6)], ['query']),
    'getAllSitterHandles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllSitters' : IDL.Func([], [IDL.Vec(Public)], ['query']),
    'getAllSubscriptionStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, SubscriptionRecord))],
        ['query'],
      ),
    'getAllTeamsAdmin' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getApiUsageLimits' : IDL.Func(
        [],
        [
          IDL.Record({
            'monthlyCount' : IDL.Nat,
            'monthlyLimit' : IDL.Nat,
            'dailyCount' : IDL.Nat,
            'dailyLimit' : IDL.Nat,
            'resetDate' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAuditLog' : IDL.Func([], [IDL.Vec(Public__7)], ['query']),
    'getAvailableHourlyWindows' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'startTime' : IDL.Text,
              'availableSitterCount' : IDL.Nat,
              'endTime' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAvailableSittersForWindow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Public)],
        ['query'],
      ),
    'getBookingHeatmapData' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'pendingCount' : IDL.Nat,
              'sitterId' : IDL.Nat,
              'date' : IDL.Text,
              'hour' : IDL.Nat,
              'confirmedCount' : IDL.Nat,
              'sitterName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getBookingsByClientEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Public__8)],
        ['query'],
      ),
    'getBookingsByClientPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Public__8)],
        ['query'],
      ),
    'getBookingsBySitter' : IDL.Func([Id], [IDL.Vec(Public__8)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoBookingAssignment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CoBookingAssignment)],
        ['query'],
      ),
    'getCompletedBookingsByContact' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Public__8)],
        ['query'],
      ),
    'getCompletedBookingsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getDealOffersBySitter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DealOffer)],
        ['query'],
      ),
    'getGrantedAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getJobThread' : IDL.Func([IDL.Nat], [IDL.Opt(JobThread)], ['query']),
    'getJobThreadMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TeamMessage)],
        ['query'],
      ),
    'getJobThreadsForTeam' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobThread)],
        ['query'],
      ),
    'getMessages' : IDL.Func([Id], [IDL.Vec(Message)], ['query']),
    'getMySupportTickets' : IDL.Func([], [IDL.Vec(Public__4)], ['query']),
    'getMyTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getNotificationsBySitter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getPayment' : IDL.Func([Id], [IDL.Opt(Public__6)], ['query']),
    'getPaymentAuditLog' : IDL.Func([Id], [IDL.Vec(Public__7)], ['query']),
    'getPaymentsByBookingIds' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Public__6)],
        ['query'],
      ),
    'getPendingInvitesForSitter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TeamInvite)],
        ['query'],
      ),
    'getPublicSitterProfile' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Nat,
              'bio' : IDL.Opt(IDL.Text),
              'reviews' : IDL.Vec(
                IDL.Record({
                  'clientName' : IDL.Text,
                  'createdAt' : IDL.Int,
                  'comment' : IDL.Opt(IDL.Text),
                  'rating' : IDL.Nat,
                })
              ),
              'name' : IDL.Text,
              'badges' : IDL.Vec(IDL.Text),
              'isActive' : IDL.Bool,
              'averageRating' : IDL.Float64,
              'profilePhotoUrl' : IDL.Opt(IDL.Text),
              'reviewCount' : IDL.Nat,
              'services' : IDL.Vec(
                IDL.Record({
                  'serviceName' : IDL.Text,
                  'duration' : IDL.Opt(IDL.Text),
                  'price' : IDL.Float64,
                })
              ),
            })
          ),
        ],
        ['query'],
      ),
    'getRecurringGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BookingGroup)],
        ['query'],
      ),
    'getRecurringGroupsByClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingGroup)],
        ['query'],
      ),
    'getRecurringGroupsBySitter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BookingGroup)],
        ['query'],
      ),
    'getReviewsBySitter' : IDL.Func([Id], [IDL.Vec(Public__5)], ['query']),
    'getServiceLogsByBooking' : IDL.Func([Id], [IDL.Vec(Public__2)], ['query']),
    'getSitterAvailability' : IDL.Func(
        [Id],
        [IDL.Vec(AvailabilityEntry)],
        ['query'],
      ),
    'getSitterBookingStats' : IDL.Func(
        [IDL.Nat],
        [SitterBookingStats],
        ['query'],
      ),
    'getSitterClientsForCRM' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CRMClient)],
        ['query'],
      ),
    'getSitterCredentials' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CredentialChecklist)],
        ['query'],
      ),
    'getSitterExtendedPublic' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SitterPublicV2Extension)],
        ['query'],
      ),
    'getSitterHandle' : IDL.Func([Id], [IDL.Opt(IDL.Text)], ['query']),
    'getSitterLicenseStatus' : IDL.Func([], [SitterLicenseStatus], ['query']),
    'getSitterPageComponents' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PageComponentVisibility)],
        ['query'],
      ),
    'getSitterPrivateData' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'emergencyContact' : IDL.Opt(IDL.Text),
              'earningsGoal' : IDL.Opt(IDL.Nat),
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getSitterProfile' : IDL.Func([Id], [Public], ['query']),
    'getSitterPublicReviews' : IDL.Func(
        [Id, IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'clientName' : IDL.Text,
              'createdAt' : IDL.Int,
              'comment' : IDL.Opt(IDL.Text),
              'rating' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getSitterReviews' : IDL.Func([Id], [IDL.Vec(Public__5)], ['query']),
    'getSitterServiceRates' : IDL.Func([Id], [IDL.Vec(Public__1)], ['query']),
    'getSitterStatsById' : IDL.Func(
        [Id],
        [
          IDL.Record({
            'repeatClientCount' : IDL.Nat,
            'totalEarningsCents' : IDL.Nat,
            'currentMonthEarningsCents' : IDL.Nat,
            'repeatClientRatePct' : IDL.Float64,
            'totalCompletedBookings' : IDL.Nat,
            'adHocJobCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSittersForSelection' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'bio' : IDL.Text,
              'owner' : IDL.Opt(IDL.Principal),
              'serviceRadius' : IDL.Opt(IDL.Nat),
              'birthdate' : IDL.Opt(IDL.Int),
              'name' : IDL.Text,
              'hourlyRate' : IDL.Nat,
              'photoUrl' : IDL.Text,
              'isAnonymized' : IDL.Opt(IDL.Bool),
              'isActive' : IDL.Bool,
              'serviceZip' : IDL.Opt(IDL.Text),
              'memberSince' : IDL.Opt(IDL.Int),
              'bookingsCompleted' : IDL.Nat,
              'acceptingNewClients' : IDL.Opt(IDL.Bool),
              'serviceRates' : IDL.Vec(
                IDL.Record({ 'service' : IDL.Text, 'ratePerHour' : IDL.Nat })
              ),
              'repeatClientRate' : IDL.Nat,
              'credentialsChecklist' : IDL.Record({
                'isProfessionalMember' : IDL.Opt(IDL.Bool),
                'hasCertificationOrTraining' : IDL.Opt(IDL.Bool),
                'hasReferences' : IDL.Opt(IDL.Bool),
                'hasBusinessLicense' : IDL.Opt(IDL.Bool),
                'isInsuredAndBonded' : IDL.Opt(IDL.Bool),
                'usesServiceAgreement' : IDL.Opt(IDL.Bool),
                'hasBackgroundCheck' : IDL.Opt(IDL.Bool),
              }),
              'rating' : IDL.Float64,
              'reviewCount' : IDL.Nat,
              'location' : IDL.Text,
              'services' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getSittersNearZip' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'bio' : IDL.Text,
              'owner' : IDL.Opt(IDL.Principal),
              'serviceRadius' : IDL.Opt(IDL.Nat),
              'birthdate' : IDL.Opt(IDL.Int),
              'name' : IDL.Text,
              'hourlyRate' : IDL.Nat,
              'photoUrl' : IDL.Text,
              'isAnonymized' : IDL.Opt(IDL.Bool),
              'isActive' : IDL.Bool,
              'serviceZip' : IDL.Opt(IDL.Text),
              'acceptingNewClients' : IDL.Opt(IDL.Bool),
              'serviceRates' : IDL.Vec(
                IDL.Record({ 'service' : IDL.Text, 'ratePerHour' : IDL.Nat })
              ),
              'rating' : IDL.Float64,
              'reviewCount' : IDL.Nat,
              'location' : IDL.Text,
              'services' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getStripeFreePlanPriceId' : IDL.Func([], [IDL.Text], ['query']),
    'getStripePublicConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'isLiveMode' : IDL.Bool,
            'priceId' : IDL.Text,
            'publishableKey' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionState' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubscriptionRecord)],
        ['query'],
      ),
    'getSupportTickets' : IDL.Func([], [IDL.Vec(Public__4)], ['query']),
    'getTeamBookings' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getTeamById' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
    'getTeamMessages' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(TeamMessage)],
        ['query'],
      ),
    'getTipsBySitter' : IDL.Func([Id], [IDL.Vec(Public__3)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminAccess' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'grantSupportAccess' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'handleStripeWebhook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'hasSupportAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'initSitterTrial' : IDL.Func([IDL.Nat], [], []),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSitterFrozen' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveTeam' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationRead' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'openSupportTicket' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'postServiceLog' : IDL.Func([Creation], [Public__2], []),
    'recordApiCall' : IDL.Func([IDL.Text], [], []),
    'recordSubscriptionPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordTip' : IDL.Func(
        [Id, Id, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'redeemCoupon' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
        [],
      ),
    'rejectSitterApplication' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resolveSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'respondToInvite' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
        [],
      ),
    'revokeAdminAccess' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfile],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'seedBaileyLinneaTeam' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
        [],
      ),
    'seedBaileyLinneaTeamWithIds' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
        [],
      ),
    'sendBookingConfirmationEmail' : IDL.Func([Id], [], []),
    'sendBookingConfirmedEmails' : IDL.Func([Id], [], []),
    'sendClientNudgeSitter' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendInvoiceToClient' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendPaymentReminder' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendRecurringBookingEmails' : IDL.Func([IDL.Text], [], []),
    'sendRecurringGroupConfirmedEmails' : IDL.Func([IDL.Text], [], []),
    'sendServiceCompletionEmail' : IDL.Func([Id], [], []),
    'sendTeamMessage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : TeamMessage, 'err' : IDL.Text })],
        [],
      ),
    'setAdminNotificationEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setApiLimits' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setCallerAsAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setFreePlanPriceId' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setInvoicePaymentMethod' : IDL.Func(
        [Id, PaymentMethodDetails],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSitterAvailability' : IDL.Func(
        [Id, IDL.Vec(AvailabilityEntry)],
        [],
        [],
      ),
    'setSitterHandle' : IDL.Func(
        [Id, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSitterPageComponents' : IDL.Func(
        [IDL.Nat, PageComponentVisibility],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSitterServiceRates' : IDL.Func([Id, IDL.Vec(Public__1)], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setStripeWebhookSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitReview' : IDL.Func([Id, IDL.Float64, IDL.Text, Id], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfreezeSitterAccount' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAdHocJobPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(PaymentMethodDetails)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateBookingStatus' : IDL.Func(
        [
          Id,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateCredentialChecklist' : IDL.Func(
        [IDL.Nat, CredentialChecklist],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateDutyStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'assigned' : IDL.Null,
            'done' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [IDL.Variant({ 'ok' : DutyAssignment, 'err' : IDL.Text })],
        [],
      ),
    'updateInvoiceAdHocItems' : IDL.Func(
        [Id, IDL.Vec(AdHocLineItem)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateInvoicePaidDate' : IDL.Func(
        [Id, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePaymentSplits' : IDL.Func([UpdateSplits], [], []),
    'updatePaymentWithDiscount' : IDL.Func(
        [Id, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateServiceCompletion' : IDL.Func(
        [
          Id,
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateServiceLogStopTime' : IDL.Func([UpdateStopTime], [], []),
    'updateSitterEarningsGoal' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSitterProfile' : IDL.Func([Update], [Public], []),
    'updateSitterProfileV2' : IDL.Func(
        [SitterProfileV2Update],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStripeConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTaskDone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : DutyTask, 'err' : IDL.Text })],
        [],
      ),
    'updateTeamSplits' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Variant({ 'ok' : Team, 'err' : IDL.Text })],
        [],
      ),
    'validateCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DealOffer, 'err' : IDL.Text })],
        ['query'],
      ),
    'validateRecurringAvailability' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(Time),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Vec(OccurrenceAvailability)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };